feat: add an exception to naming convention
ridedott/eslint-config pull request #756
Opened 2021-01-19 15:50 UTC by mad-it

2021-01-19 15:55 UTC, mad-it commented
@viestat Can you help me with the tests failing? I extended the expiration but that didnt work 🤔

2021-01-19 17:09 UTC, viestat requested changes
Tests for this configuration are missing.

I can led you a hand tomorrow if you need help. I will also take a look at why the test where the TODO was extended is failing.

2021-01-19 17:09 UTC, viestat commented on rules/typescript.js
> +      },
This should be accompanied by its own test.

In general terms, you need to add a passing fixture and a failing fixture.

2021-01-20 08:54 UTC, mad-it commented
@viestat Added some tests with https://github.com/ridedott/eslint-config/pull/756/commits/ce66df6cebe6de904ab62eb714f991e671167716.
However I did notice that we have 2 of the same rules:  `array-func/prefer-flat-map` and `unicorn/prefer-flat-map`. Probably have to disable one of them. Can you help out with this?

2021-01-20 10:00 UTC, viestat approved these changes

2021-01-20 10:04 UTC, viestat commented
> However I did notice that we have 2 of the same rules: `array-func/prefer-flat-map` and `unicorn/prefer-flat-map`. Probably have to disable one of them. Can you help out with this?

I can create a separate PR removing either one of them.

> Edit: Think we can use this PR to update all the deps as well? I fixed the `TODO` and this was the only thing blocking all the other PR's. That way we can group the release with 1 big release.

Im not sure what the benefit would be, however we would loose the relevance of the PR, if we would like to revert it, we would revert a lot of changes. I say we merge it and deal with the dependencies separately. Either way dependabot will try to update to the latest version.

2021-01-20 10:08 UTC, merged